################################# Default configuration ###################
# provide your domain here
baseURL = "http://ec2-13-127-26-38.ap-south-1.compute.amazonaws.com/"
# theme
theme = "dot"
# site title
title = "Medicare"
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

publishDir = "docs"

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]
name = "Introduction"
url = "introduction"
weight = 1

[[menu.main]]
name = "How to use"
url = "howtouse"
weight = 2

[[menu.main]]
name = "How it works"
url = "howitworks"
weight = 3

# [[menu.main]]
# name = "Faq"
# url = "faq"
# weight = 1

# [[menu.main]]
# name = "contact"
# url = "contact"
# weight = 2

# # Dropdown menu
# [[menu.main]]
# weight = 3
# name = "docs"
# hasChildren = true

#   [[menu.main]]
#   parent = "docs"
#   name = "Installation"
#   url = "installation"
#   weight = 1

#   [[menu.main]]
#   parent = "docs"
#   name = "Billing and Pricing"
#   url = "billing-pricing"
#   weight = 2

#   [[menu.main]]
#   parent = "docs"
#   name = "Features"
#   url = "features"
#   weight = 3


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
# primary_color = "#02007e"
# body_color = "#f9f9f9"
# text_color = "#636363"
# text_color_dark = "#242738"
# white_color = "#ffffff"
# light_color = "#f8f9fa"
primary_color = "#D1BB02"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#F9F7F0"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "#"
  
[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "Home"
copyright = "The Hugo Documents are copyright © [gethugothemes](https://gethugothemes.com/) 2020."

# banner
[Languages.en.params.banner]
title = "Medicare Echannelling Website"
subtitle = "Medicare providing highquality and fast service"
bg_image = "images/slide-four.jpg"

